server:
  #这个是web容器的端口，并非dubbo服务监听的端口。
  port: 9080
  servlet:
    context-path: /points
management:
  server:
    port: 8088 #管理端口调整成8088
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
    health:
      show-details: always

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  application:
    module: points
    name: points-service
  datasource:
    dynamic:
      primary: system
      strict: true
      datasource:
        system:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/system?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: points_3
          password: points123!@#
        account:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/account?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: points_3
          password: points123!@#
        customer:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/customer?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: points_3
          password: points123!@#
        merchant:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/merchant?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: points_3
          password: points123!@#
      mp-enabled: true
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  # sql存放的位置
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wt2024.**.entity
  global-config:
    # 数据库相关配置
    db-config:
      #数据库 MYSQL，ORACLE，DB2
      db-type: MYSQL
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      #驼峰下划线转换
      table-underline: true
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    #刷新mapper 调试神器
    refresh: true
    #缓存 Sql 解析初始化
    sql-parser-cache: false
    #是否控制台 print mybatis-plus 的 LOGO
    banner: false
  # 原生配置
  configuration:
    # sql执行语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

# swagger开启
swagger:
  enable: true
# 是否停用Knife4j文档
knife4j:
  production: false
  setting:
    enableOpenApi: false

logging:
  node-name: dev

local:
  thread:
    switch: Y

